// Created by iWeb 3.0.4 local-build-20151103

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_2:new IWStrokeParts([{rect:new IWRect(-2,2,4,119),url:'About_Me_files/stroke_16.png'},{rect:new IWRect(-2,-2,4,4),url:'About_Me_files/stroke_17.png'},{rect:new IWRect(2,-2,204,4),url:'About_Me_files/stroke_18.png'},{rect:new IWRect(206,-2,5,4),url:'About_Me_files/stroke_19.png'},{rect:new IWRect(206,2,5,119),url:'About_Me_files/stroke_20.png'},{rect:new IWRect(206,121,5,5),url:'About_Me_files/stroke_21.png'},{rect:new IWRect(2,121,204,5),url:'About_Me_files/stroke_22.png'},{rect:new IWRect(-2,121,4,5),url:'About_Me_files/stroke_23.png'}],new IWSize(208,124)),stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,126),url:'About_Me_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'About_Me_files/stroke_9.png'},{rect:new IWRect(2,-2,204,4),url:'About_Me_files/stroke_10.png'},{rect:new IWRect(206,-2,4,4),url:'About_Me_files/stroke_11.png'},{rect:new IWRect(206,2,4,126),url:'About_Me_files/stroke_12.png'},{rect:new IWRect(206,128,4,4),url:'About_Me_files/stroke_13.png'},{rect:new IWRect(2,128,204,4),url:'About_Me_files/stroke_14.png'},{rect:new IWRect(-2,128,4,4),url:'About_Me_files/stroke_15.png'}],new IWSize(208,130)),stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,403),url:'About_Me_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'About_Me_files/stroke_1.png'},{rect:new IWRect(2,-2,473,4),url:'About_Me_files/stroke_2.png'},{rect:new IWRect(475,-2,5,4),url:'About_Me_files/stroke_3.png'},{rect:new IWRect(475,2,5,403),url:'About_Me_files/stroke_4.png'},{rect:new IWRect(475,405,5,4),url:'About_Me_files/stroke_5.png'},{rect:new IWRect(2,405,473,4),url:'About_Me_files/stroke_6.png'},{rect:new IWRect(-2,405,4,4),url:'About_Me_files/stroke_7.png'}],new IWSize(477,407)),stroke_3:new IWStrokeParts([{rect:new IWRect(-2,2,4,199),url:'About_Me_files/stroke_24.png'},{rect:new IWRect(-2,-2,4,4),url:'About_Me_files/stroke_25.png'},{rect:new IWRect(2,-2,200,4),url:'About_Me_files/stroke_26.png'},{rect:new IWRect(202,-2,4,4),url:'About_Me_files/stroke_27.png'},{rect:new IWRect(202,2,4,199),url:'About_Me_files/stroke_28.png'},{rect:new IWRect(202,201,4,4),url:'About_Me_files/stroke_29.png'},{rect:new IWRect(2,201,200,4),url:'About_Me_files/stroke_30.png'},{rect:new IWRect(-2,201,4,4),url:'About_Me_files/stroke_31.png'}],new IWSize(204,203))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('About_Me_files/About_MeMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');detectBrowser();adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
